
server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/seokjeatuiti/config-repository

# actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:          